[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "requests>=2.32.3",
    "schedule>=1.2.2",
    "tenacity>=9.1.2",
]
